apiVersion: v1
kind: Pod
metadata:
  name: nginix
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  



# kubectl create -f filename.yml

kubectl describe  pod nginx

# kubectl get pods


apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: httpd-frontend
  template:
    metadata:
      labels:
        name: httpd-frontend
    spec:
      containers:
      - name: httpd-frontend
        image: httpd:2.4-alpine


apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest




architecture goes like create pods -> service-> deployments 



to start with deployments 


apply kubeclt create -f <deployment files> will run my pods
apply kubeclt create -f <service files>
