apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deploy
  labels:
    name: postgress-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgress-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgress-pod
      labels:
        name: postgress-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgress
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "md5"
